const DEFAULT_BRANCH_CITY = "Город подразделения"
const DEFAULT_BRANCH_ADDRESS = "Адрес подразделения"

const DEFAULT_EMPLOYEE_FIRST_NAME = "Имя"
const DEFAULT_EMPLOYEE_LAST_NAME = "Фамилия"
const DEFAULT_EMPLOYEE_MIDDLE_NAME = "Отчество"
const DEFAULT_EMPLOYEE_JOB_TITLE = "Должность"

export {
    DEFAULT_BRANCH_CITY, DEFAULT_BRANCH_ADDRESS, DEFAULT_EMPLOYEE_FIRST_NAME, DEFAULT_EMPLOYEE_LAST_NAME,
    DEFAULT_EMPLOYEE_MIDDLE_NAME, DEFAULT_EMPLOYEE_JOB_TITLE
}