const DEFAULT_BRANCH_CITY = "Город филиала"
const DEFAULT_BRANCH_ADDRESS = "Адрес филиала"

const DEFAULT_EMPLOYEE_FIRST_NAME = "Имя"
const DEFAULT_EMPLOYEE_LAST_NAME = "Фамилия"
const DEFAULT_EMPLOYEE_MIDDLE_NAME = "Отчество"
const DEFAULT_EMPLOYEE_JOB_TITLE = "Должность"

const TOAST_ANIMATION_TIME = 220

export {
    DEFAULT_BRANCH_CITY, DEFAULT_BRANCH_ADDRESS, DEFAULT_EMPLOYEE_FIRST_NAME, DEFAULT_EMPLOYEE_LAST_NAME,
    DEFAULT_EMPLOYEE_MIDDLE_NAME, DEFAULT_EMPLOYEE_JOB_TITLE, TOAST_ANIMATION_TIME
}